default_platform(:android)

platform :android do

  desc "Parent 앱 Firebase 배포"
  lane :distribute_parent do
    gradle(
      task: "assemble",
      flavor: "parent",
      build_type: "Release"
    )
    firebase_app_distribution(
      app: "1:112221989354:android:1f2e2d59592d1186c5ea93",
      android_artifact_type: "APK",
      android_artifact_path: "app/build/outputs/apk/parent/release/app-parent-release.apk",
      groups: "internal-testers",
      release_notes: "내부 테스트 빌드입니다.",
      service_credentials_file: "fastlane/firebase-service-account.json"
    )
  end

  desc "Child 앱 Firebase 배포"
  lane :distribute_child do
    gradle(
      task: "assemble",
      flavor: "child",
      build_type: "Release"
    )
    firebase_app_distribution(
      app: "1:112221989354:android:0ca46b5786af2699c5ea93",
      android_artifact_type: "APK",
      android_artifact_path: "app/build/outputs/apk/child/release/app-child-release.apk",
      groups: "internal-testers",
      release_notes: "내부 테스트 빌드입니다.",
      service_credentials_file: "fastlane/firebase-service-account.json"
    )
  end

  desc "두 앱 모두 배포"
  lane :distribute_all do
    distribute_parent
    distribute_child
  end

end